### PR TITLE
Nx workspace and dependencies updated to latest versions

### PR DESCRIPTION
**Pull request by sjimenez77**
Besides, linting and tests have been fixed and useless tests removed.

### CODE REVIEW

**Comment by suprishi** [comment]
I find compilation errors for 2 samples: ionic-basic-pwa and angular-electron-test. Attaching screenshot for reference.

image


image

Can you confirm they are working at your end?

**Comment by suprishi** [comment]
To resolve the error in ionic-basic-pwa, plugins have to be installed and imported from their own packages after updating capacitor/core to 3.x version:

`import { Camera, CameraResultType } from '@capacitor/camera';`

**Comment by sjimenez77** [comment]
Thanks @suprishi, the error is now fixed and also applied the same strategy with the `Toast` Capacitor plugin that had the same issue. 

Besides that, I am wondering if it is interesting to add the nxtend plugin for Nx as it covers most Ionic and Capacitor capabilities, updates and so on for Nx workspaces https://nxtend.dev/. Maybe you would like to take a look.

**Comment by suprishi** [comment]
> Thanks @suprishi, the error is now fixed and also applied the same strategy with the `Toast` Capacitor plugin that had the same issue.
> 
> Besides that, I am wondering if it is interesting to add the nxtend plugin for Nx as it covers most Ionic and Capacitor capabilities, updates and so on for Nx workspaces https://nxtend.dev/. Maybe you would like to take a look.

Thanks for fixing the error @sjimenez77 .
As for the nxtend plugins, we have @nxtend/capacitor and @nxtend/ionic-angular already installed. Is there something else you are referring to or am I missing something?

**Comment by sjimenez77** [comment]
@suprishi, I forgot I had already installed them 😆 !!! Anyhow, I think this PR can be merged now, right?

**Comment by suprishi** [comment]
> @suprishi, I forgot I had already installed them 😆 !!! Anyhow, I think this PR can be merged now, right?
> 
> Regarding documentation I think that it could be interesting to add some references to the nxtend docs in our ionic section.

Yes, I will merge this PR now.
The [ionic PWA guide](https://github.com/devonfw/devon4ts/wiki/guide-ionic-pwa) does have some guidelines while developing with both ng and nx. But maybe they are not highlighted enough. We can create issues for them and discuss there.
